;;; gmsh-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gmsh-mode.el

(autoload 'gmsh-mode-completion-at-point "gmsh-mode" "\
GMSH function to be used for the hook `completion-at-point-functions'." t)
(autoload 'gmsh-mode "gmsh-mode" "\
GMSH mesh generator major mode.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.gmsh\\'" . gmsh-mode))
(add-to-list 'auto-mode-alist '("\\.geo\\'" . gmsh-mode))
(register-definition-prefixes "gmsh-mode" '("gmsh-"))

;;; End of scraped data

(provide 'gmsh-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gmsh-mode-autoloads.el ends here
