;;; auctex-latexmk-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from auctex-latexmk.el

(autoload 'auctex-latexmk-setup "auctex-latexmk" "\
Add LatexMk command to TeX-command-list.")
(register-definition-prefixes "auctex-latexmk" '("Latexmk-sentinel" "TeX-run-latexmk" "auctex-latexmk-"))

;;; End of scraped data

(provide 'auctex-latexmk-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; auctex-latexmk-autoloads.el ends here
