;;; enh-ruby-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from enh-ruby-mode.el

(autoload 'enh-symbol-or-null-p "enh-ruby-mode" "\
Return true if X is either a symbol or null. Used for defcustom safe check.

(fn X)")
(autoload 'enh-ruby-mode "enh-ruby-mode" "\
Enhanced Major mode for editing Ruby code.

\\{enh-ruby-mode-map}

(fn)" t)
(register-definition-prefixes "enh-ruby-mode" '("enh-ruby-" "erm-" "extra-col-%"))

;;; End of scraped data

(provide 'enh-ruby-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; enh-ruby-mode-autoloads.el ends here
